### ISSUE TITLE
Open in VSCode from current tab's URL?

### ISSUE THREAD

**Issue by vergenzt** [aberonni/open-in-vscode#11]
As I understand it, currently, in order to use this extension there has to be an anchor tag on the current page _pointing_ to a Github URL.

I wish that I could open the _current_ page's URL as a file in VSCode by simply clicking the extension!

This could use the `activeTab` permissions -- which appears to have been designed for this exact use case!

https://developer.chrome.com/docs/extensions/mv3/manifest/activeTab/#motivation

> The activeTab permission gives an extension temporary access to the currently active tab when the user invokes the extension - for example by clicking its action. Access to the tab lasts while the user is on that page, and is revoked when the user navigates away or closes the tab.
>
> ...
>
> **Motivation**
>
> **Consider a web clipping extension that has a [action](https://developer.chrome.com/docs/extensions/reference/action/) and [context menu item](https://developer.chrome.com/docs/extensions/reference/contextMenus/). This extension may only really need to access tabs when its browser action is clicked, or when its context menu item is executed.**
> 
> Without activeTab, this extension would need to request full, persistent access to every web site, just so that it could do its work if it happened to be called upon by the user. This is a lot of power to entrust to such a simple extension. And if the extension is ever compromised, the attacker gets access to everything the extension had.
> 
> In contrast, an extension with the activeTab permission only obtains access to a tab in response to an explicit user gesture. If the extension is compromised the attacker would need to wait for the user to invoke the extension before obtaining access. And that access only lasts until the tab is navigated or is closed.

**Comment by aberonni** [comment]
I've uploaded a new version of the extension with this functionality to the web store. Hopefully it will be reviewed and published soon. Lmk if it doesn't work for you.
