### ISSUE TITLE
I can't open it correctly,  when I opened it，there is a '-' in path, but in my base path, there is no '-'

### ISSUE THREAD

**Issue by xiangdongbu** [aberonni/open-in-vscode#18]

**Comment by aberonni** [comment]
What link are you trying to open?

**Comment by xiangdongbu** [comment]
> What link are you trying to open?

Link like this：https://gitlab.xxxxx.com/xxxx-it/-/tree/develop

**Comment by xiangdongbu** [comment]
> What link are you trying to open?

Or like this: https://gitlab.xxxxx.com/xxxx-it/-/tree/develop/packages/test/src/pages/home/index.tsx

Neither of them worked

**Comment by aberonni** [comment]
Closing as a duplicate of #15 - feel free to reopen if the issue is a different one
