### ISSUE TITLE
Cannot open projects on windows

### ISSUE THREAD

**Issue by wangzhijun97** [aberonni/open-in-vscode#5]
Cannot open projects on Windows when I setted a directory. It does not appear to have been downloaded locally. Is the path format wrong?
![image](https://user-images.githubusercontent.com/30629705/108322970-105d0f00-7201-11eb-88df-7667bce4dbbf.png)
![image](https://user-images.githubusercontent.com/30629705/108322864-f02d5000-7200-11eb-8b64-4844e376750c.png)

**Comment by aberonni** [comment]
You have to download it locally yourself. From [the README](https://github.com/aberonni/open-in-vscode#usage):

> **The extension expects the repository you are browsing to already be cloned into the folder in the options page.**
